import src from "./assets/chad.steele.technical.director.senior.software.engineer.manager.r&d.jpeg"
import qr from "./assets/qr.chadsteele.com.png"

export default {
	qr: qr,
	header: {
		name: "Chad Steele",
		creds: "BSEE, MESE",

		links: [
			{
				icon: "linkedin",
				text: "/in/chadsteele",
				link: "https://linkedin.com/in/chadsteele",
			},
			{
				icon: "web",
				text: "chadsteele.com",
				link: "https://chadsteele.com",
			},
			{
				icon: "email",
				text: "chad@chadsteele.com",
				link: "mailto:chad@chadsteele.com",
			},
		],
	},
	profile: {
		pic: {src, alt: "chad steele, senior engineer, technical lead R&D"},
	},
	workExperience: {
		title: "Experience",
		subtitle:
			"10+ Years of Technical Leadership, Innovation and Engineering Excellence",
		jobs: [
			{
				company: "Cyber Reality, inc. R&D",
				title: "Senior Consultant",
				dates: "2023 - Present",
				description: [
					"Designed and developed an AI app that supports real time conversations with doctors, lawyers, etc. by prompting the user with relevant questions given the content and context of the current conversation",
					"Developed an AI and LLM app to detect fake news, untruths, and deception in conversation and media",
					"Developed a crypto gambling game platform",
					"Technologies used: Python, GCP, Azure, Node.js, SolidJS, React Native",
				],
			},
			{
				company: "ObvioHealth",
				title: "Team Lead Medical R&D",
				dates: "2021 - 2023",
				description: [
					"Led development of AI-powered medical tools utilizing technologies like Onnx, TensorFlow, and Python",
					"Developed innovative AR solutions using ARjs and Unity for enhanced user experiences",
					"Proficient in full-stack development with Node.js, SolidJS, React Native, and other key technologies",
					"Strong technical skills including React, Python, AI/ML, Cloud Computing, and more",
					"Reported to Brian Cohn, Director of R&D",
				],
			},
			{
				company: "Audibene / Hear.com",
				title: "Senior R&D Engineer",
				dates: "2020 - 2021",
				description: [
					"Led various R&D projects to develop their teleaudiology platform",
					"Developed a novel remote hearing diagnostics test",
					"Technologies used: Meteor, Node.js, Typescript, React, Redux, C#, C++, WebRTC, Twilio, PubNub, AWS, Docker, and Terraform",
					"Reported to Tonio Knuth, Global Head of Tech and Innovation",
				],
			},
			{
				company: "Slync.io",
				title: "Sr. Fullstack Software Engineer",
				dates: "2019 - 2020",
				description: [
					"Developed a world-class logistics orchestration platform and served some of the biggest companies in the world",
					"Focused on technologies like Elasticsearch, Kibana, React, Redux, Typescript, and Node.js",
					"Other skills: Cloud Computing, Node.js,TypeScript, React.js, jQuery, CSS",
					"Reported to Jason Selvidge, VP of Engineering",
				],
			},
			{
				company: "Digital Ridge, inc",
				title: "CTO / Partner",
				dates: "2012 - 2019",
				description: [
					"Led a digital agency specializing in persona-based marketing, booking, and conversions for the destination and ski industries",
					"Developed an AR gamified app that enabled guests to quickly find offers and opportunities at resorts and destinations",
					"Developed an innovative headless CMS using Lucene Solr, .NET, and Node, resulting in improved performance, conversions, SEO, and personalized content",
					"Partner: Brice Cave, CEO",
				],
			},
			{
				company: "ACTIVE Network",
				title: "Technical Director / Architect",
				dates: "2010 - 2012",
				description: [
					"Led over 100 engineers with teams in Colorado, San Diego, Philadelphia, Canada and China",
					"Improved web infrastructure and the web development pipeline for 1000s of Active clients in 100s of vertical markets",
					"Primary tech was .NET, HTML, Javascript, jQuery, CSS and SQL, but I introduced Lucene Solr and Java as an architectural enhancement and radically improved performance and features",
					"Reported to Scott Gustlin, General Manager",
				],
			},
			{
				company: "Healthgrades, inc",
				title: ".NET/Java Application Architect",
				dates: "2009 - 2010",
				description: [
					"Led the architectural design and development of high-performance internal applications and integration solutions, ensuring seamless business operations",
					"Pioneered the application architecture for a leading medical website, adeptly managing over 1 million daily visits with a robust tech stack including Lucene Solr, Apache, C#,MVC.NET 3.0, Razor, SQL, TFS 2010, ASP.NET, and Java",
					"Reported to Greg Haynie, VP of Technology",
				],
			},
			{
				company: "State of Wyoming",
				title: ".NET Enterprise Architect",
				dates: "2007 - 2009",
				description: [
					"Worked with over 40 different state agencies, their vendors, constituents and contractors to improve the enterprise and streamline workflows",
					'I\'m especially proud of our new regulatory platform "NRG Steward" that helped manage trillions of dollars of land, water, livestock, natural gas, coal, oil and other natural resources. The platform was so successful that Alaska and Oklahoma bought the platform',
					"Developed using Agile, C#, .NET, jQuery, Project Management, CSS, Java",
					"Reported to Howard Sweeney, Director, Governor’s Office of the CTO",
				],
			},
			{
				company: "Colorado DOT, Parson’s Engineering",
				title: "Intelligent Transportation Architect",
				dates: "2006 - 2007",
				description: [
					"Led the overhaul and successful deployment of Denver's TREX Intelligent Transportation System, enhancing automated incident detection capabilities",
					"Fostered collaborative partnerships with Colorado and Florida Department of Transportation agencies to ensure project alignment and success",
					"Leveraged advanced programming skills in C++, COM, VisualBasic, and Java, coupled with Oracle and PL/SQL database expertise, to deliver robust transportation solutions",
					"Reported to Gary Gonzalez, Director",
				],
			},
			{
				company: "Cobe BCT, inc R&D",
				title: "Team Lead / Architect",
				dates: "2000 - 2005",
				description: [
					"Led a high-performing team of 12 engineers as Software Architect and Team Lead within a medical R&D division, overseeing a budget exceeding $4 million",
					"Instrumental in achieving global recognition through numerous international awards, solidifying the product's industry leadership for nearly two decades (refer to Spectra Optia)",
					"Medical Device US Patents #6,790,195, #6,810,719, #7,013,715, and #7,108,672",
					"Reported to Tim Gordon, Director of R&D",
				],
			},
			{
				company: "Cyber Reality, inc",
				title: "Owner / Consultant",
				dates: "2000 - Present",
				description: [
					{
						project: "MicroMotion R&D",
						details: [
							"Designed and developed a cutting-edge, highly profitable real-time embedded system application in C++ for precise oil flow measurement and control using the Coriolis effect",
							"US Patents: #5,653,887, #5,941,84, #6,318,156, #6,497,674, #6,564,619",
						],
					},
					{
						project: "Level (3) Communications",
						details: [
							'Designed and developed an enterprise-wide "customer first" portal using Javascript, jQuery, C#, and Lucene Solr. This optimized access to internal apps and SQL data, increasing productivity for sales, marketing, and CSR employees.',
							"Increased productivity, ease of use, and reduced onboarding training from 6 weeks to 6 days",
						],
					},
					{
						project: "Frontier Airlines",
						details: [
							"Developed the new Frontier Airlines website (www.FrontierAirlines.com)",
							"Developed front-end and back-end services integrating with Sabre and other web services ",
							"Used Java, Struts, J2EE, SQL, IBM Eclipse, Javascript, CSS, and XML",
						],
					},
					{
						project: "Microsoft / FRx Software",
						details: [
							"Designed and developed a new Ecommerce and CRM system for FRx and its partners to manage and coordinate internet sales and marketing efforts",
							"Uses C#, SQL, ASP.NET and Microsoft CRM",
						],
					},
					{
						project: "Qwest / CenturyLink",
						details: [
							'As Sr. Architect, led a team of 30+ C++ and Java developers on a $40 million project called "wireless wizard".',
							"Consolidated wireless phone service and empowered CSRs to manage multiple business systems",
							"Enabled USWest/Qwest to provide a single phone number for both cell and home",
							"Integrated data and workflows from 9 data centers for managing accounting, support services, etc., in addition to call routing",
						],
					},
				],
			},
		],
	},
	aboutMe: [
		{
			title: "About Me",
			subtitle: "Simple Solutions to Complex Problems",
			items: [
				"As an accomplished Technical Director, Architect, and Lead Software Engineer, I bring over a decade of expertise and innovation to the art of software engineering",
				"I am a proven leader, engineer, and innovator. I'm a passionate software developer. I have current skills in cutting-edge front and back-end technologies, object-oriented and event oriented programming languages, search engines, object and relational databases",
				"I am well-versed in DevOps methodologies, CICD pipelines, and the latest containerization technologies",
				"I am an organized manager, and am data and process driven. My teams create context before content, goals before objectives, and celebrate losses and lessons",
				"I am especially effective with remote developers because I encourage ownership, thoughtful communication, and am objective oriented",
			],
		},
		{
			title: "Interests",
			subtitle: "Volunteer, Coach, Mentor and Facilitator",
			items: [
				"Over 20 years of experience coaching and facilitating transformational leadership conversations with youth at risk, mentors, parents, and other stakeholders with the following non-profit organizations: boldleaders.org, sosoutreach.org, playforpeace.org, challengeday.org, coloradoyouthatrisk.org",
				"Volunteered with animal welfare NGOs focused on apes, dolphins, and whales: janegoodall.org, orangutan.org, gorillafund.org, thedolphininstitute.org",
				"Enjoys kayaking, scuba diving, kitesurfing, and playing the drums",
			],
		},
	],

	education: {
		title: "Education",
		items: [
			{
				institution: "UNIVERSITY OF COLORADO, BOULDER",
				degree: "MESE in Computer Engineering",
				achievements: [
					"Specialized in UX, Artificial Intelligence and Engineering Management",
					"Dean's List and Honor Role",
					"Authored a thesis on innovative GUI design for medical devices",
				],
			},
			{
				institution: "UNIVERSITY OF WYOMING",
				degree: "BSEE in Computer Engineering",
				achievements: [
					"President's Honor Roll",
					"Employed as Senior Software Engineer for the Dean's Office of the College of Engineering",
					"Employed by the Dept of Zoology and developed robotics for neural research on bats, rats and frogs",
					"Won the International Easter Seal Award for an innovative device that empowerd severely disabled using thick film polymers",
					"My work resulted in a whole new department and degree and several million dollar grants for the University",
					"Proud member of the Order of the Engineer",
					"Member of the UW Ski Team",
					"Managed operations - Sigma Chi House Manager",
				],
			},
		],
	},
	skills: {
		title: "Skills",
		items: [
			{
				category: "Leadership",
				skills: [
					"Technical Leadership",
					"Innovation",
					"Engineering Excellence",
					"Proven Leader",
					"Organized Manager",
					"Data-Driven",
					"Process-Driven",
					"Encourages Ownership",
					"Thoughtful Communication",
					"Objective-Oriented",
					"Led Development",
					"Led Projects",
					"Led Digital Agency",
					"Led Engineers",
					"Led Architectural Design",
					"Worked with State Agencies",
					"Led Overhaul",
					"Led High-Performing Team",
				],
			},
			{
				category: "Engineering",
				skills: [
					"Software Engineering Expertise",
					"Innovation",
					"Passionate Developer",
					"Cutting-Edge Technologies",
					"Object-Oriented Programming",
					"Event-Oriented Programming",
					"Search Engines",
					"Relational Databases",
					"DevOps",
					"CICD Pipelines",
					"Containerization Technologies",
					"Robotics Development",
					"Neural Research",
					"AI App Development",
					"LLM App Development",
					"Fake News Detection",
					"AR Solutions Development",
					"Full-Stack Development",
					"Node.js",
					"SolidJS",
					"React Native",
					"React",
					"Python",
					"AI/ML",
					"Cloud Computing",
					"Novel Remote Hearing Diagnostics",
					"Meteor",
					"Node",
					"Typescript",
					"Redux",
					"C#",
					"C++",
					"WebRTC",
					"Twilio",
					"PubNub",
					"AWS",
					"Docker",
					"Terraform",
					"Logistics Orchestration Platform",
					"ElasticSearch",
					"Kibana",
					"AR Gamified App Development",
					"Headless CMS Development",
					"Lucene Solr",
					".NET",
					"Improved Web Infrastructure",
					"Web Development Pipeline",
					"Application Architecture",
					"Agile",
					"Advanced Programming Skills",
					"Oracle",
					"PL/SQL",
					"Database Expertise",
					"Co-Inventor",
					"US Patents",
				],
			},
			{
				category: "Business",
				skills: [
					"Team Management",
					"Goal-Setting",
					"Loss Celebration",
					"Digital Agency Leadership",
					"Persona-Based Marketing",
					"Booking",
					"Conversions",
					"Destination Industry",
					"Ski Industry",
					"Improved Web Infrastructure",
					"Web Development Pipeline",
					"Active Clients",
					"Vertical Markets",
					"Worked with State Agencies",
					"Vendors",
					"Constituents",
					"Contractors",
					"Enterprise Improvement",
					"Streamlined Workflows",
					"Regulatory Platform",
					"NRG Steward",
					"Land Management",
					"Water Management",
					"Livestock Management",
					"Natural Gas",
					"Coal",
					"Oil",
					"Natural Resources Management",
					"Agile",
					"Advanced Programming Skills",
					"Collaborative Partnerships",
					"Project Alignment",
					"Success",
					"High-Performing Team Leadership",
					"Software Architect",
					"Team Lead",
					"Medical R&D Division",
					"Budget Management",
					"Global Recognition",
					"International Awards",
					"Industry Leadership",
					"Innovation",
					"Intellectual Contribution",
				],
			},
		],
	},
}
